# Generated by Django 3.1 on 2020-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.CharField(default='no avatar', max_length=50),
        ),
    ]
