# Generated by Django 3.1 on 2020-08-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200810_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbs',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
